### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by andress134** [dropout1337/Omegle-Traffic-Bot#1]
Hey sir can u make same bot for other website? i know some good websites without any protection with alot traffic
@dropout1337

**Comment by cChimney** [comment]
just drop the sites here

**Comment by andress134** [comment]
> just drop the sites here

https://anunturigayprahova.wgz.ro/
https://anuntonline.wgz.ro/
https://anunturinetv.wgz.ro/

These sites have a lot of traffic, most of them are gay people
It has a lot of pages for each city
Is it possible for this script to spam these sites by accessing each page with each city on the site?

**Comment by cChimney** [comment]
Is possible but i see like no traffic at all on these sites the only messages are mine
